activity = statement* EOF // path test
statement = path / EOL

path = name? hop+ // path to some instance set represented by a name
hop = '/' (rnum / name) // rnum must be first since name can also match rnum
name = word (NAME_GLUE word)* // One word or a sequence of delimited words (name used for most model elements)

NAME_GLUE = r'[ _]' // delmits words within a name
rnum = r'O?R[1-9][0-9]*' // Relationship number (name used for relationships)
word = r'[A-Za-z][A-Za-z0-9]*'
LINEWRAP = EOL SP* // end of line followed by optional indent on next line
EOL = SP* COMMENT? '\n' // end of line: Comments, blank lines, whitespace we can omit from the parser result
COMMENT = '//' r'.*' // Comment slashes don't work if included in the regular expression for some reason
SP = ' '