activity = statement* EOF // inst test
statement = instance_set? EOL

instance_set = (call / selection / name)
selection = name '(' SP* select_phrase SP* ')'
select_phrase = (CARD ',' SP* criteria / criteria / CARD )
criteria = attr_comparison (',' SP* attr_comparison)*
attr_comparison = RANK? REFLEX? name comparison
comparison = SP* (':' / '==' / COMPARE) SP* scalar
CARD = '1' / '*'
RANK = '+^' / '-^'
REFLEX = 'its.'
COMPARE = ':' / '==' / '>=' / '>' / '<=' / '<'

call = name '.' operation
operation = name '(' SP* (supplied_params SP*)? ')'
supplied_params = param (',' param)*
param = name (SP* ':' SP* scalar)?

scalar = call / attr_access / name
attr_access = name '.' name

name = word (NAME_GLUE word)* // One word or a sequence of delimited words (name used for most model elements)
NAME_GLUE = r'[ _]' // delmits words within a name
word = r'[A-Za-z][A-Za-z0-9]*'
LINEWRAP = EOL SP* // end of line followed by optional indent on next line
EOL = SP* COMMENT? '\n' // end of line: Comments, blank lines, whitespace we can omit from the parser result
COMMENT = '//' r'.*' // Comment slashes don't work if included in the regular expression for some reason
SP = ' '